// User details action type
export const SIGNUP_DETAILS_REQUEST = 'SIGNUP_DETAILS_REQUEST';
export const SIGNUP_DETAILS_SUCCESS = 'SIGNUP_DETAILS_SUCCESS';
export const SIGNUP_DETAILS_FAIL = 'SIGNUP_DETAILS_FAIL';

// Login details action types
export const LOGIN_DETAILS_REQUEST = 'LOGIN_DETAILS_REQUEST';
export const LOGIN_DETAILS_SUCCESS = 'LOGIN_DETAILS_SUCCESS';
export const LOGIN_DETAILS_FAIL = 'LOGIN_DETAILS_FAIL';

// Secret Key action types 
export const CLIENT_SECRET_REQUEST = 'CLIENT_SECRET_REQUEST';
export const CLIENT_SECRET_SUCCESS = 'CLIENT_SECRET_SUCCESS';
export const CLIENT_SECRET_FAIL = 'CLIENT_SECRET_FAIL';


// Payment Details action types 
export const PAYMENT_DETAILS_REQUEST = 'PAYMENT_DETAILS_REQUEST';
export const PAYMENT_DETAILS_SUCCESS = 'PAYMENT_DETAILS_SUCCESS';
export const PAYMENT_DETAILS_FAIL = 'PAYMENT_DETAILS_FAIL';

// Update  Sttaus action types 
export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';
